Repository op19-it-edu/api-server, pull requests merged in 2020-01, with the labels that each got.

#16 golangの環境構築手順をreadmeに記載
  README.md
Labels: レビュー済（王）, レビュー済（糸井）

#17 golang実行環境確認用PR
  main.go
Labels: レビュー済（王）, レビュー済（糸井）

#19 開発用DBを爆速でセットアップするファイル追加
  README.md
  db_setup/.env
  db_setup/docker-compose.yml
Labels: レビュー済（王）, レビュー済（糸井）

#20 echoを導入して、ブラウザから`hello, word`を出力させるAPIを作成する
  controller/controller.go
  main.go
Labels: レビュー済（糸井）

#22 gitignoreファイルの追加
  .gitignore
Labels: レビュー待ち, レビュー済（野口）

#24 環境構築手順の修正(#8)
  README.md
Labels: レビュー済（糸井）, レビュー済（野口）

#21 gormを導入して、DB操作を絡めたAPIを作成する
  controller/controller.go
  go.mod
  go.sum
  model/db.go
  model/entity.go
  model/user.go
  server.go
Labels: レビュー済（王）, レビュー済（糸井）
